type Candidate {
  candidate: String
  sdpMLineIndex: Int
  sdpMid: String
  usernameFragment: String
}

input CandidateInput {
  candidate: String
  sdpMLineIndex: Int
  sdpMid: String
  usernameFragment: String
}

enum CandidateType {
  CALLEE
  CALLER
}

type ChatMessage {
  message: String!
  roomUuid: String!
  sender: String!
}

scalar Date

type Mutation {
  addIceCandidates(candidateType: CandidateType!, iceCandidates: [CandidateInput!]!, offerSdp: String!, roomUuid: String!): Boolean!
  createRoom(name: String!): Room!
  sendMessage(message: String!, roomUuid: String!, sender: String!): String!
  sendOfferAnswer(answer: OfferInput!, offerSdp: String!, roomUuid: String!): Boolean!
  sendUserOffer(offer: OfferInput!, roomUuid: String!, userUuid: String!): Boolean!

  """Mutation to trigger subscription serverStatus !"""
  testSubscription: Boolean! @deprecated(reason: "Use only for testing")
}

type Offer {
  sdp: String
  type: RTCSdpType!
}

input OfferInput {
  sdp: String
  type: RTCSdpType!
}

type ParticiantAction {
  action: Offer!
  participant: Participant!
}

type Participant {
  uuid: String!
}

type Query {
  isAlive: Boolean!
  joinRoom(roomUuid: String!, userUuid: String!): Boolean
  ping: String!
}

enum RTCSdpType {
  answer
  offer
  pranswer
  rollback
}

type Room {
  uuid: String!
}

type Subscription {
  isConnectionReady: Boolean!

  """
  Subscription to server status, trigger using mutation `testSubscription` 
  """
  serverStatus: Float! @deprecated(reason: "Use only for testing")
  subscribeToAnswers(
    """Offer sdp"""
    offerSdp: String!

    """Room uuid"""
    roomUuid: String!
  ): Offer!
  subscribeToCandidate(candidateType: CandidateType!, offerSdp: String!, roomUuid: String!): [Candidate!]!
  subscribeToMessages(roomUuid: String!): ChatMessage!
  subscribeToOffers(
    """Room uuid"""
    roomUuid: String!

    """User uuid"""
    userUuid: String!
  ): Offer!
  subscribeToParticipants(roomUuid: String!): Participant!
}